### ISSUE TITLE
Make web app installable (PWA) [Feature]

### ISSUE THREAD

**Issue by adeekshith** [mawoka-myblock/sd-replacement#3]
Can add configuration to the web app to make it a progressive web app which can then be installed on phones just like a native app considering user has a supported browser(Firefox/Chrome,...) and supported launcher (most stock launchers work).

Did not try your app yet (will do it soon!) but saw your web app and also noticed you are trying to create a mobile app with Cordova. Having a mobile app is good but if a web app can do the job, many may prefer that. So thought will share this with you 😊

Instructions: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

**Comment by mawoka-myblock** [comment]
Thanks! Will look at it asap!

**Comment by mawoka-myblock** [comment]
I think I fixed it, but it doesn't work...

**Comment by adeekshith** [comment]
> I think I fixed it, but it doesn't work...

Oh, I'll see what's going on

**Comment by adeekshith** [comment]
~~Do you have a branch where you added that?~~

Saw it is already in gh-pages

**Comment by mawoka-myblock** [comment]
That's the commit: [Here](https://github.com/mawoka-myblock/sd-replacement/commit/0d4fe17d6d0438092abc74195ce1ceb0c9557878)

**Comment by adeekshith** [comment]
This worked for me on Firefox mobile with default launcher that comes with Samsung. However, some third party Android launchers may not support it very well.

Also, we need to add a service worker to make it work with Chrome as per the [MDN article](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs#requirements)

|     Installing on Firefox    |      Opening from launcher      |
| ------------- |:-------------:|
| ![sd-client PWA install](https://user-images.githubusercontent.com/2568945/121790894-e1045080-cba9-11eb-9b02-5eaf765f4a54.jpeg)      | ![sd-client PWA opened](https://user-images.githubusercontent.com/2568945/121790906-eeb9d600-cba9-11eb-8cee-63b95a85eec5.jpeg) |

**Comment by mawoka-myblock** [comment]
> This worked for me on Firefox mobile with default launcher that comes with Samsung. However, some third party Android launchers may not support it very well.
> 
> Also, we need to add a service worker to make it work with Chrome as per the [MDN article](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs#requirements)
> 
> Installing on Firefox	Opening from launcher
> ![sd-client PWA install](https://user-images.githubusercontent.com/2568945/121790894-e1045080-cba9-11eb-9b02-5eaf765f4a54.jpeg)	![sd-client PWA opened](https://user-images.githubusercontent.com/2568945/121790906-eeb9d600-cba9-11eb-8cee-63b95a85eec5.jpeg)

Oh, yes I remember! I only tested on Chrome, but I understood the article wrong. I thought that I only need a service worker for Chrome on Android and not for every chrome version!

**Comment by mawoka-myblock** [comment]
Ok, I had a look at the service worker and I think it is too complicated for this feature. I mean, it works on Firefox! So, I'll close the issue for now, because I'm too lazy to learn how to program a service worker and how it works!

**Comment by mawoka-myblock** [comment]
Finished it, thanks @adeekshith for your help!

**Comment by adeekshith** [comment]
Awesome! 👏😃
Glad you were able to figure that out. I thought of taking a look at service workers too but could not do it yet.

**Comment by mawoka-myblock** [comment]
The service worker I used caches pictures but that's it! Not worth diving into it I think! (IMHO)
